Repository 2020mt93213/Pune_BusRoutes, pull requests merged in 2021-04, with the labels that each got.

#6 Added conclusion of plot
  01_Ntbk_PuneBusRoutes_DataAnalysis.ipynb
Labels: documentation

#8 Feature: Raw images for buses in motion gif
  01_Ntbk_PuneBusRoutes_DataAnalysis.ipynb
Labels: feature

#10 Fixed issue #9, image filename as per timestamp
  01_Ntbk_PuneBusRoutes_DataAnalysis.ipynb
Labels: process

#12 Fixing issue #11
  01_Ntbk_PuneBusRoutes_DataAnalysis.ipynb
Labels: bug

#17 Update README.md
  README.md
Labels: documentation
